server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
     datasource:
        driver-class-name: org.postgresql.Driver
        url: postgres://znklynufpdglsa:e3e623bb35ebbebd5000f5358b9ce5d1ada68fe49d5b2192ca89f4d81053b527@ec2-52-21-153-207.compute-1.amazonaws.com:5432/dasra5b0jdj85p

        username: znklynufpdglsa
        password: e3e623bb35ebbebd5000f5358b9ce5d1ada68fe49d5b2192ca89f4d81053b527
     jpa:
          show-sql: true
          database-platform: org.hibernate.dialect.PostgreSQLDialect
          generate-ddl: true
          hibernate:
            ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0.0